'use client';

import { useEffect, useState } from 'react';
import { searchPublications } from '@/lib/api';
import type { Publication } from '@/lib/types';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Bot, Loader2, Search, Share2, Star } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { summarizeMedicalPublication } from '@/ai/flows/ai-summarize-medical-publications';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';

function PublicationCard({ pub }: { pub: Publication }) {
    const [summary, setSummary] = useState('');
    const [isLoadingSummary, setIsLoadingSummary] = useState(false);
    const [isDialogOpen, setIsDialogOpen] = useState(false);

    const handleSummarize = async () => {
        setIsLoadingSummary(true);
        setIsDialogOpen(true);
        try {
            // The abstract might be short or unavailable, so we pass title and journal too.
            const contentToSummarize = `${pub.title}. Journal: ${pub.journal}. Abstract: ${pub.abstract}`;
            const result = await summarizeMedicalPublication({ publicationContent: contentToSummarize });
            setSummary(result.summary);
        } catch (error) {
            console.error('AI summary failed:', error);
            setSummary('Sorry, we were unable to generate a summary for this publication.');
        } finally {
            setIsLoadingSummary(false);
        }
    };

    return (
        <>
            <Card>
                <CardHeader>
                    <CardTitle className="text-lg font-bold">{pub.title}</CardTitle>
                    <CardDescription>{pub.authors.join(", ")} &middot; <span className="italic">{pub.journal}, {pub.year}</span></CardDescription>
                </CardHeader>
                <CardContent>
                    <p className="text-sm text-muted-foreground line-clamp-2">{pub.abstract}</p>
                </CardContent>
                <CardFooter className="flex justify-between items-center">
                    <Button variant="ghost" size="sm" onClick={handleSummarize} disabled={isLoadingSummary}>
                        <Bot className="mr-2 h-4 w-4" />
                        AI Summary
                    </Button>
                    <div className="flex gap-1">
                        <Button variant="ghost" size="icon">
                            <Star className="h-4 w-4" />
                        </Button>
                        <Button variant="ghost" size="icon">
                            <Share2 className="h-4 w-4" />
                        </Button>
                    </div>
                </CardFooter>
            </Card>
            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle className="font-headline">AI Summary of {pub.id}</DialogTitle>
                        <DialogDescription>This summary is generated by AI and may not be fully accurate.</DialogDescription>
                    </DialogHeader>
                    {isLoadingSummary ? (
                        <div className="flex items-center justify-center p-8">
                            <Loader2 className="h-8 w-8 animate-spin text-primary" />
                        </div>
                    ) : (
                        <div className="prose prose-sm max-h-[60vh] overflow-y-auto rounded-md border p-4">
                            <p>{summary}</p>
                        </div>
                    )}
                </DialogContent>
            </Dialog>
        </>
    )
}


export default function PublicationsPage() {
    const [publications, setPublications] = useState<Publication[]>([]);
    const [loading, setLoading] = useState(false);
    const [searchTerm, setSearchTerm] = useState('');
    const [searchQuery, setSearchQuery] = useState('');


    useEffect(() => {
        async function fetchPublications() {
            if (!searchQuery) {
                setPublications([]);
                return;
            };
            setLoading(true);
            const fetchedPublications = await searchPublications(searchQuery);
            setPublications(fetchedPublications);
            setLoading(false);
        }
        fetchPublications();
    }, [searchQuery]);

    const handleSearch = (e: React.FormEvent) => {
        e.preventDefault();
        setSearchQuery(searchTerm);
    };

    return (
        <div className="space-y-6">
            <div>
                <h1 className="font-headline text-3xl font-bold">
                    Explore Medical Publications
                </h1>
                <p className="text-muted-foreground">
                    Stay up-to-date with the latest medical research.
                </p>
            </div>

            <div className="flex items-center gap-4">
                <form onSubmit={handleSearch} className="flex-1 max-w-lg relative">
                    <Input
                        placeholder="e.g. cancer therapy, immunology..."
                        className="pr-10"
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                    />
                    <Button type="submit" size="icon" variant="ghost" className="absolute right-1 top-1/2 -translate-y-1/2 h-8 w-8" disabled={loading}>
                      {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}
                    </Button>
                </form>
            </div>

            {loading ? (
                <div className="grid gap-6">
                    {Array.from({ length: 3 }).map((_, i) => (
                        <Card key={i}>
                            <CardHeader>
                                <Skeleton className="h-6 w-3/4" />
                                <Skeleton className="h-4 w-1/2" />
                            </CardHeader>
                            <CardContent>
                                <div className="space-y-2">
                                  <Skeleton className="h-4 w-full" />
                                  <Skeleton className="h-4 w-5/6" />
                                </div>
                            </CardContent>
                            <CardFooter className="flex justify-between items-center">
                                <Skeleton className="h-8 w-28" />
                                <div className="flex gap-2">
                                  <Skeleton className="h-8 w-8 rounded-full" />
                                  <Skeleton className="h-8 w-8 rounded-full" />
                                </div>
                            </CardFooter>
                        </Card>
                    ))}
                </div>
            ) : (
                 publications.length > 0 ? (
                    <div className="grid gap-6">
                        {publications.map((pub) => (
                            <PublicationCard key={pub.id} pub={pub} />
                        ))}
                    </div>
                ) : (
                    <Card className="flex items-center justify-center h-64 border-dashed">
                        <div className="text-center">
                            <p className="text-lg font-medium">No Publications Found</p>
                            <p className="text-sm text-muted-foreground">Try adjusting your search terms.</p>
                        </div>
                    </Card>
                )
            )}
        </div>
    )
}
