'use client';

import { summarizeClinicalTrial } from '@/ai/flows/ai-summarize-clinical-trials';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import type { ClinicalTrial } from '@/lib/types';
import { Bot, Loader2, Share2, Star, ExternalLink } from 'lucide-react';
import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { useFavorites } from '@/context/favorites-provider';

export default function TrialCard({ trial }: { trial: ClinicalTrial }) {
  const [summary, setSummary] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const { isFavorite, toggleFavorite } = useFavorites();
  const favorite = isFavorite(trial.id);

  const handleSummarize = async () => {
    setIsLoading(true);
    setIsDialogOpen(true);
    try {
      const result = await summarizeClinicalTrial({ trialDetails: trial.description + ' ' + trial.eligibility });
      setSummary(result.aiSummary);
    } catch (error) {
      console.error(error);
      setSummary('Sorry, we were unable to generate a summary for this trial.');
    } finally {
      setIsLoading(false);
    }
  };
  
  const statusColor = trial.status === 'Recruiting' ? 'bg-green-500' : 'bg-yellow-500';

  return (
    <>
      <Card className="flex flex-col">
        <CardHeader>
          <div className="flex items-start justify-between gap-4">
            <CardTitle className="text-lg font-bold leading-tight">{trial.title}</CardTitle>
            <Badge variant="outline" className="shrink-0">
              <span className={`w-2 h-2 rounded-full ${statusColor} mr-2`}></span>
              {trial.status}
            </Badge>
          </div>
          <CardDescription>{trial.id} &middot; {trial.phase}</CardDescription>
        </CardHeader>
        <CardContent className="flex-grow">
          <p className="text-sm text-muted-foreground line-clamp-3">{trial.description}</p>
          <div className="mt-4 flex flex-wrap gap-2">
            {trial.tags.slice(0,3).map(tag => (
              <Badge key={tag} variant="secondary">{tag}</Badge>
            ))}
          </div>
        </CardContent>
        <CardFooter className="flex justify-between items-center">
          <div className="flex gap-1">
            <Button variant="ghost" size="sm" onClick={handleSummarize}>
              <Bot className="mr-2 h-4 w-4" />
              AI Summary
            </Button>
            <Button variant="ghost" size="sm" asChild>
                <a href={trial.url} target="_blank" rel="noopener noreferrer">
                    <ExternalLink className="mr-2 h-4 w-4" />
                    Source
                </a>
            </Button>
          </div>
          <div className="flex gap-1">
            <Button variant="ghost" size="icon" onClick={() => toggleFavorite(trial, 'trial')}>
              <Star className={`h-5 w-5 ${favorite ? 'text-yellow-400 fill-yellow-400' : 'text-muted-foreground'}`} />
            </Button>
            <Button variant="ghost" size="icon">
              <Share2 className="h-4 w-4" />
            </Button>
          </div>
        </CardFooter>
      </Card>
      
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="font-headline">AI Summary of {trial.id}</DialogTitle>
            <DialogDescription>This summary is generated by AI and should not replace professional medical advice.</DialogDescription>
          </DialogHeader>
          {isLoading ? (
            <div className="flex items-center justify-center p-8">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          ) : (
            <div className="prose prose-sm max-h-[60vh] overflow-y-auto rounded-md border p-4">
              <p>{summary}</p>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </>
  );
}
